// import Layout from 'components/layout/main';
import Layout from 'components/layout/admin';
import Head from 'next/head';
import React from 'react';
// import NewDrawer from './NewForm/NewDrawer';

function Home() {
    return (
        <div>
            {/* Searching */}
            <Head>
                <title>Admin</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </div>
    );
}
Home.Layout = Layout;
export default Home;
